CREATE TABLE if not exists public.sport
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_sport PRIMARY KEY (id)
);