CREATE TABLE if not exists public.athlete
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name           VARCHAR(255) NOT NULL,
    social_name         VARCHAR(255),
    birth_date          date         NOT NULL,
    cpf                 VARCHAR(11),
    locale_id           BIGINT       NOT NULL,
    weight              DOUBLE PRECISION,
    height              DOUBLE PRECISION,
    biceps_measurement  DOUBLE PRECISION,
    forearm_measurement DOUBLE PRECISION,
    chest_measurement   DOUBLE PRECISION,
    thigh_measurement   DOUBLE PRECISION,
    calf_measurement    DOUBLE PRECISION,
    CONSTRAINT pk_athlete PRIMARY KEY (id)
);

ALTER TABLE public.athlete
    ADD CONSTRAINT FK_ATHLETE_ON_LOCALE FOREIGN KEY (locale_id) REFERENCES public.locale (id);


CREATE TABLE if not exists public.community
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_community PRIMARY KEY (id)
);

create table if not exists public.membership
(
    athlete_id BIGINT NOT NULL,
    community_id BIGINT NOT NULL,
    membership_status VARCHAR(100),
    constraint membership_pkey PRIMARY KEY (athlete_id, community_id)
);

ALTER TABLE public.membership
    ADD CONSTRAINT FK_ATHLETE_ON_MEMBERSHIP FOREIGN KEY (athlete_id) REFERENCES public.athlete(id);
ALTER TABLE public.membership
    ADD CONSTRAINT FK_COMMUNITY_ON_MEMBERSHIP FOREIGN KEY (community_id) REFERENCES public.community(id);