CREATE TABLE public.gym
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255)                            NOT NULL,
    rules     TEXT,
    locale_id BIGINT,
    CONSTRAINT pk_gym PRIMARY KEY (id)
);

ALTER TABLE gym
    ADD CONSTRAINT FK_GYM_ON_LOCALE FOREIGN KEY (locale_id) REFERENCES public.locale (id);

create table public.practicable
(
    sport_id BIGINT NOT NULL ,
    gym_id BIGINT NOT NULL,
    practicable_state varchar(100),
    constraint practicable_pkey PRIMARY KEY (sport_id, gym_id)
);

ALTER TABLE public.practicable
    ADD CONSTRAINT FK_GYM_ON_PRACTICABLE FOREIGN KEY (gym_id) references public.gym(id);

ALTER TABLE public.practicable
    ADD CONSTRAINT FK_SPORT_ON_PRACTICABLE FOREIGN KEY (sport_id) references public.sport(id);