ALTER TABLE public.booking ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.booking ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE public.community ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.community ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE public.gym ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.gym ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE public.locale ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.locale ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE public.membership ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.membership ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE public.practicable ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.practicable ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE public.athlete ADD COLUMN  created_by  TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE public.athlete ADD COLUMN  modified_by TIMESTAMP WITHOUT TIME ZONE;