server:
  port: 8888
spring:
  profiles:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_URL}:8080/realms/quattys/protocol/openid-connect/certs
