server:
  port: 8888
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
            issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_URL}:8080/realms/quattys/protocol/openid-connect/certs
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    open-in-view: true
    generate-ddl: true
  flyway:
    encoding: UTF-8
    validate-on-migrate: true
    enabled: false


keycloak:
  auth-server-url: http://${KEYCLOAK_URL}:8080/
  realm: ${REALM}
  resource: ${RESOURCE_SERVICE}
  credentials:
    secret: ${RESOURCE_SERVICE_CLIENT}
