server:
  port: 88
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/quattys/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
    generate-ddl: true
  flyway:
    encoding: UTF-8
    validate-on-migrate: true
    enabled: false
  h2:
    console:
      path: /h2-console
      enabled: true

keycloak:
  auth-server-url: http://localhost:8080/
  realm: quattys
  resource: sportive-service
  credentials:
    secret: gNECE4NB8dH93l4WjKaYxfD5GeK0v263

